# Generated by Django 5.0.2 on 2024-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_client_password_alter_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dateCommande1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dateLastCommande',
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
