# Generated by Django 4.1.7 on 2024-05-26 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boutique", "0006_alter_lignevente_produit_alter_lignevente_quantite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
    ]
