# Generated by Django 5.0.2 on 2024-02-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dateCommande1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dateLastCommande',
            field=models.DateField(null=True),
        ),
    ]
