# Generated by Django 5.0.2 on 2024-02-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_alter_lignevente_produit_alter_lignevente_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
