# Generated by Django 4.1.7 on 2024-05-26 13:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Dol de Bretagne", max_length=180, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="FR", max_length=2, verbose_name="country"
            ),
        ),
    ]
