name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
        pip install celery==5.2.7
        pip install importlib-metadata==4.0.0

    - name: Install pipdeptree
      run: pip install pipdeptree

    - name: Check dependency tree
      run: pipdeptree

    - name: Show installed packages
      run: pip list

    - name: Show Celery location
      run: python -c "import celery; print(celery.__file__)"

    - name: Run Tests
      run: |
        python backend/boutique_django/manage.py test core_apps.boutique.tests
