name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: sqlite:///db.sqlite3

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r .github/workflows/requirements.txt
        pip install celery==5.2.7
        pip install importlib-metadata==4.0.0

    - name: Run tests
      run: |
        source venv/bin/activate
        python backend/boutique_django/manage.py test boutique.tests
